### ISSUE TITLE
Open Source Design @ Ushahidi

### ISSUE THREAD

**Issue by justinscherer** [MozillaFestival/open-leaders-6#109]
Project lead: @justinscherer
Mentor: @thebonface

**Comment by justinscherer** [comment]
## Week 2
- [ ] Create a new issue for project
- [ ] complete self assessment
- [ ] make sure Zoom works
- [ ] Watch the intro video
- [ ] Draft a vision statement
- [ ] Comment on the vision statements of at least two other projects
- [ ] Complete open canvas and link it here
- [ ] Make a roadmap draft and link it here

**Comment by Erioldoesdesign** [comment]
I'm doing my week 3 assignment where I feedback on others tickets :)

"contribute more than code" Do you think being more specific here would be useful? Or do you not want to limit the contributors potential?

**Comment by justinscherer** [comment]
# Roadmap

## Short Term
* Audit the experience of contributing to the OSS version of Ushahidi
* Create a space in the repo for OSS Design contributions
* Create Asset Libraries for Sketch and AdobeXD
* Write a design contribution guide

## Medium Term
* Establish how the design contributions make it to the developers
* Reach out to the existing open source design community
* User test the contribution process with 5 other designers
* Promote the open source design effort

## Long Term
* Iterate on the asset libraries, contribution guides, design -> developer processes
* Write whitepapers with learnings on OSS design processes
* Continue building the OSS design contributor community

**Comment by justinscherer** [comment]
> "contribute more than code" Do you think being more specific here would be useful? Or do you not want to limit the contributors potential?

Good question @Erioldoesdesign . I suppose you contribute anything from translations, to copy, to usability testing

**Comment by justinscherer** [comment]
### Open Canvas

![open canvas](https://user-images.githubusercontent.com/29209303/46161436-c7c4e580-c242-11e8-9af9-1562afb83f20.png)

**Comment by justinscherer** [comment]
**Post mentor call to do list**
- [ ] make a space in the Ushahidi Platform repo for design contribution
- [ ] refine roadmap
- [ ] refine contributors and users part of open canvas -> break them down a bit more. At least 5 contributor and user profiles that are a bit narrower (number of years)
- [ ] refine problem number ``3``
- [ ] reach out to open source design community
- [ ] more detail to the open source design problem
- [ ] contributor code of conduct
- [ ] invite an expert

**Comment by JazzBrotha** [comment]
**Open canvas feedback**
Your open canvas has a strong connection to your vision statement. The problems for designers that your project solves are clearly presented with the use of an open source framework. The value proposition offers a clear benefit to the Internet Health movement.

**Comment by KevZawacki** [comment]
Hi @justinscherer, super clear Open Canvas 👍 

Excited to see this project unfold!

**Comment by madhurish** [comment]
Hi @justinscherer , loved your Open Canvas. In your contributor profiles would it help to have graphic designers to make graphic resources and assets for the open source projects?

**Comment by akeshavan** [comment]
This is a great open canvas, I'm really excited about this project!

**Comment by seandiggity** [comment]
your canvas is comprehensive, and I think it's great that attracting more diverse contributors is a central goal.  Would it also be possible to provide the design files in a Free/Libre format like SVG, not just Sketch and Adobe formats?  From a licensing standpoint, proprietary formats (especially those with binary blobs) can be problematic (many copyleft licenses require a human-readable source format).
