### ISSUE TITLE
Openscapes

### ISSUE THREAD

**Issue by jules32** [MozillaFestival/open-leaders-6#20]
Project Lead: @jules32

Mentor: Camille Maumet

Welcome to OL6, Cohort E! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***
Before Week 1 (Sept 13): Your first mentorship call
- [ ] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [ ] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 20): First Cohort Call (Open by Design)
- [ ] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [ ] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [ ] Check the [Syllabus](https://mzl.la/ol6-syllabus-culture-track) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 27): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 4): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus-culture-track) for more detailed weekly notes and assignments past week 4.

**Comment by jules32** [comment]
Mission statement ([guidance here](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/)):

**I’m working with early career environmental scientists to increase the value and practice of open data science in environmental science so that all environmental scientists can efficiently and collaboratively work with data and communicate solutions to environmental challenges.**

**Comment by jules32** [comment]
## Openscapes Roadmap draft

**Project Mission & Summary**

To open up the landscapes of environmental science through open community, data, and code.

We are increasing the value and practice of open data science in environmental science by focusing on three things: engaging researchers, empowering them with existing open tools and communities, and amplifying their successes. We work 1:1 with early career researchers and help them improve their own practices by understanding how they work and identifying their next steps (as a recipe) toward openness. We help them become **champions** to enable other through their lab groups, their teaching, their seminars, and study groups on campus. Openscapes.org focuses has an engaging homepage, empowering resources and “recipes” from the champions, and a blog and twitter handle (@openscapes) to amplify successes (and challenges) and build community.

**What do we need to do?** [TODO, this is is copied from [STEMM](https://github.com/KirstieJane/STEMMRoleModels/issues/1)]
This issue is our roadmap. It's a place to start to investigate the myriad of issues that you can contribute to. Check out the different milestones listed below, but feel free to explore the issues by label too.
Please check out our contribution guidelines and code of conduct to help you get started, and the README for an overview if you haven't read it yet!


**Milestone: create slide decks (engagement)**  
Build off current versions in GoogleSlides, (not starting from scratch) consider switching to xaringan (Rmarkdown)

 - [x] 10 minute version for Oct 17 (NCEAS working group)
 - [x] 45 minute version for Oct 24 (WHOI invited seminar)

**Milestone: create public TED-style pitch (engagement)**

- [x] 5-7 minutes without slides Oct 25 (MozFest)

**Milestone: website mockup**  
May only be in Google doc at this stage. Will ultimately have content for engagement, empowerment, and amplify, but will start with engagement and beginnings of empowerment to launch the site 

- [x] Get feedback at Mozfest (Oct 25-28)

**Milestone: reach out to prospective champions (engagement)**

- [x] Finalize list of cohort 1 champions to work with through 2018 
- [x] Craft and send emails
- [x] Meet in person with 2 new champions (Oct 19-20), formalize engagement questions

**HOW ARE YOU GOING TO ASK PEOPLE TO CONTRIBUTE AND HELP ME - TODO** 

- For the talk: 
- For the website mockup:
- For reaching out to the champions:

**Comment by jules32** [comment]
## Open Canvas draft

https://docs.google.com/presentation/d/1eJVNN-wDiQdWlRN5u6D6lDpySZoo2viiWli1rqsl_FU/edit?usp=sharing

**Comment by jules32** [comment]
The repo is [here](https://github.com/Openscapes/leadership).

- [x] add LICENSE
- [x] add README
- [ ] add CONTRIBUTING (figure out contributing ladders)
- [ ] add CODE_OF_CONDUCT
