### ISSUE TITLE
Ushahidi

### ISSUE THREAD

**Issue by Erioldoesdesign** [MozillaFestival/open-leaders-6#32]
Project Leads: @erioldoesdesign @justinscherer

Mentors: @triaslucia @denefi

**Comment by andyl** [comment]
I'm work on communication tools for first responders - interested in offline / low bandwidth / intermittent connections & look forward to hearning more about your project.

**Comment by Erioldoesdesign** [comment]
Link to my Moz recommended [Open Canvas 1](https://docs.google.com/presentation/d/1XBQ79d3o4bad-55dW3jN7MdBc1Ie9nR4tTc_fx5Ov6o/edit?usp=sharing)

<img width="785" alt="screen shot 2018-12-05 at 11 43 42" src="https://user-images.githubusercontent.com/11681324/49513543-3cdb1980-f889-11e8-9867-e0cc0de16dac.png">

Link to my Mentor recommended [Open Canvas 2 TBC](https://docs.google.com/presentation/d/1L3yk1KGtWRi8D_9ppq4M_1zMm5DgVtLicP3PNDhxvz8/edit?usp=sharing)

**Comment by justinscherer** [comment]
Vision statement feedback:

> understand what the barriers to contribution are and test/build a method/framework so that Community development workers, international development workers, activists and volunteers can be an integral part of the process and can see clearly how their experiences and input affects the tools that will help them do good with their causes.

Perhaps state explicitly what they are contributing to and to what end?

**Comment by triaslucia** [comment]
> ### Vision or Mission Statement - WIP
> 
> I’m working with Community development workers, international development workers, activists and volunteers to first, understand what the barriers to contribution are and test/build a method/framework so that Community development workers, international development workers, activists and volunteers can be an integral part of the process and can see clearly how their experiences and input affects the tools that will help them do good with their causes.

You got all what you need in your vision...I think it just need some small text correction :) 
For instance if you explain here you want to go User-based, that will help /support theidea of taking into account their experiences and it´ll frame the way you´ll do it. 
Great job so far @Erioldoesdesign  !! 
👍

**Comment by owenjoseph** [comment]
Hi @Erioldoesdesign. I’m very interested in following this issue, as both a non-techie myself and as a project leader who would like to encourage / enable more non-techie contributors.

FWIW in my experience with our project at Hack for L.A., the main obstacles I perceive are:
- potential non-techie contributors assume they can’t add value,
- design or content-focused contributors aren’t continuously involved in the process, and lose interest, and
- we’re using GitHub, which, as a platform, is not inviting to non-techie types (I’ve got 5 years experience with JIRA as a Project Manager, and scaling the Git-mountain was still an undertaking for me) 

I'm still new to GitHub, so I wonder if you or others reading have experience using it as a version control system for non-code assets.

Cheers!

**Comment by Erioldoesdesign** [comment]
# Roadmap

## Goal 1 - Engage with at least one group that has used Ushahidi platform before. 

- [x] Send an initial engagement message to Bristol Women’s Voice (BWV) https://bristolstreetharassmentproject.ushahidi.io/

- [x] Ascertain whether BWV would want to be updated on the progress of these issues and the contributions made by them

- [x] Send a request to SWIDN (International development workers meet-up) to see if I can do a lunchtime session or an evening talk on OSS and the barriers to them.

- [x] Send a request to Bristol tech Volunteers to see if I can do a lunchtime session or an evening talk on OSS and the barriers to them.

- [x] Send a request to Bristol Tech 4 Good to see if I can do a lunchtime session or an evening talk on OSS and the barriers to them.

- [ ] Reach out to one international group  as a longer term project outreach. ([Mapping Media Freedom](https://mappingmediafreedom.org/))



## Goal 2 - Via survey information collection, discussion, interviews or other research methods; discover/validate the barriers to contributing to OSS tech/code projects are.


- [x] Have a set of questioning for a 30 minute meeting ready for BWV meeting

- [x] Have a set of questioning for a 30 minute meeting ready for SWIDN meeting/workshop

- [x] Assess and turn research from Hacktoberfest and Mozfest into guidance on barriers

- [ ] Sound/video record the meetings/workshops

- [ ] Based off in-person learnings and desk research, review tools which could address the barriers to contribution.

- [ ] Compile tools and assess gaps

### Stretch goal!
- [ ] Meeting with an international group Mapping Media Freedom


## Goal 3 - Design a potential way for the int dev, activists and volunteers to contribute based off the information gathered in goals 1 & 2

- [ ] Create a google form/type form of these issues and trial this method of responding/contributing to issues.

- [ ] Investigate a way the above can be automated

- [ ] Investigate other methods of contribution including but not limited to: Setting meetings with a developer & an international development worker (IDW), larger hack events that are IDW focussed and dev focused to get all people in the room. (Some progress)

- [x] Go through backlog of Ushahidi tickets and pick 5 that are relevant to BWV’s work plan around street harassment - Done

- [ ] Go through backlog of Ushahidi tickets and pick 5 that are relevant to general international dev workers work.

### Stretch goal!
- [x] Go through backlog of Ushahidi tickets and pick 5 that are relevant to Mapping Media Freedom’s goals


## Goal 5 - Gain at least 5 contributions from my target groups or beyond.

- [ ] Through the meetings and pilot test case with BWV’s gain 5 contributions to the platform through the method’s identified in early goals.

- [ ] Publish findings in article and paper format. 


### Stretch goal!
- [ ] Retain engagement from a target group. Investigate a weekly or monthly contribution ‘newsletter’ ‘email alert’ or regular events.

**Comment by Erioldoesdesign** [comment]
**Licenses:**

https://github.com/ushahidi/platform/blob/develop/LICENSE.md
https://github.com/ushahidi/platform-client/blob/develop/LICENSE.md
https://github.com/ushahidi/platform-pattern-library/blob/master/LICENSE.md

**Comment by Erioldoesdesign** [comment]
**Findings from Hacktoberfest:**

- Dev groups need 1-2 big issues to work on together that are broken down into clear tasks.
- Less exp'd devs need smaller tickets to work on individually to feel sense of achievement.
- For a stand alone event, 4 hours is not enough time to make much progress on an issue.
- Context from the users (my target group) is useful but best summarised.
- Facilitating a group session of a mix of developers/coders and the target group is beneficial to the process but difficult to organise.

**Findings from Mozfest session:**

- Accessing educational institutions for a source of contributors requires moderation/engagement/curriculum by-in.
- Again, user context is useful but complex. 'Needs translation/simplification'.

**Findings from Google code-in:**

- TBC Google code-in still in progress

**Comment by Erioldoesdesign** [comment]
# Findings from meeting with Bristol Women's voice (BWV):

## The issues picked for BWV are:

**Obfuscation (formerly "Anonymization") v2 #3181**
https://github.com/ushahidi/platform/issues/3181

Notes: The admins find it useful to know precise location of a report/response in order to lobby local authorities/government for better provisions (more street lighting, remove bushes etc.) in high volume response/post areas or extreme instances. Allows them to take direct action. 
There is no need to know a persons name but certain demo graphics are very useful for informing policy.
Admins across BWV all know the details given in a post and there are policies in place internally to safeguard that information. Within this org there is no need to have multiple levels of access to users data at the moment.


**Semi-Anonymous Posting #1571**
https://github.com/ushahidi/platform/issues/1571

Notes: BWV currently ask demographic questions as part of their survey set up but indicate it would be useful to be able to collect this in a protected way. BWV never want a responder to become a 'user' e.g. sign up for an account on the deployment as the nature of the responses/posts are typically one off or even if there was multiple responses/posts by one person then they do not need to be connected yet. 
Responders don't tend to check back after posting once or multiple times unless they experience another issue. Follow up is hard so a way of following up with a responder reliably and privately would be useful



**Anonymization of Reporters Mobile #2685**
https://github.com/ushahidi/platform/issues/2685

Notes: Hesitation to automatically record responder mobile location. Responder may not be in the place that it happened and may be reporting it later at home or days/weeks after the incident. Responders should also be notified that their GPS could be used before it is used.

**Allow changing map icons #1436**
https://github.com/ushahidi/platform/issues/1436

Notes: BWV say this could be useful for outside campaign uses but it's not essential. More useful would be colour coding (which exists but they struggled to discover) 
They might be interested in icons that describe the type of offence (speech bubble as hate speech etc.)
They are most interested in this if it helps/encourages other responders understand and write their own responses.

**Custom Icons #1941**
https://github.com/ushahidi/platform/issues/1941

Notes: See above re. changing icons.

BWV then talked about some innovations that would be useful without issues to prompt including:
- A critical mass or 'hotspot' of responses/posts in either a configurable or non-configurable area that will send an email alert to the admin to investigate. Non config would be any geo area that receives over 10 posts. Configurable could be a combo of number of posts in geo area, type of post, timing of post etc. Semi connected to ML investigation: https://github.com/ushahidi/platform/issues/1681

- Ability to automatically redirect a responder to a webpage or document that will help them e.g. they send a report about hate speech -> get a message about a resource by BWV to recover from Hate Speech threats or where to go for legal advice. No current issue in Ushahidi repo.

- Ability to have weekly email digests of new posts. Admin often forgets to check in on deployment so would like an email digest of new posts. Covered in a private issue within an Ushahidi account. 

## Glossary:

Platform = An instance of the Ushahidi data collection product is referred to as 'platform' or 'a deployment'

Report/Response/Post = A single instance of a person completing a response to a survey on a particular deployment.

Responder = A person responding to one of Bristol Women's Voice surveys on the Ushahidi platform about street harassment

Admin/s = The person/s that own the platform deployment of Bristol Women's Voice street harassment

**Comment by Erioldoesdesign** [comment]
Who are my users? - Write Personas to validate

## Non-techy personas

**Persona 1 - (Individuals in) Charities/NGOs/Non-profit orgs - Fans & Skeptics - Need Most.**
These are the people that work within small to medium Charities/NGOs/Non-profit orgs. They tend not to have a technical person/s in the org and don’t typically rely on tech to solve their problems. They could be national or international working or both. They are typically small staffed and overworked and low on resources/cash for tech.

**Persona 2 - Individual international development workers/consultants. Fans - Need.**
These people typically advise small, medium and large Charities/NGOs/Non-profit orgs and help build programs (for the charitable work) and proposals/grant writing that can include tech as part of the program. They are a swing factor for orgs that engage with them.

**Persona 3 - Volunteers & Activists - Fans & Skeptics - Need most.**
These are the people that drive small to large causes and initiative usually within their local/national areas. They are typically more focused on the cause and the people impacted than the ‘tech’ and how that can serve the cause. They are fans of ethical means in which to achieve ‘good’ for their cause but skeptical that tech can solve complex ‘human’ problems

## Techy personas (support the effort)
**Persona 4 - News, media and Journalists - Skeptics.**
These are the people that hold our org reputation in their hands to some extent. They can also be part volunteer/activist persona too. They are hard to convince and we are both wary of them and them of us. There are dangers with working with these people due to the potential reputation risk.

**Persona 5 - Technical people working in Charities/NGOs/Non-profit orgs - Fans - Need most.**
These are the people that work in the orgs alongside the non-technical people. They don’t typically need help/convincing of the benefits of tech solutions to humanitarian problems but they tend to be a strained resource (if they exist) in these orgs. They could be a great source of insight and feedback on how to engage and work with the non-techy people in these orgs. There is also potential to have these people act as a gateway/buddy to contribution.

**Persona 6 - Technical people not yet volunteering - Need.**
These people are technical but they sit outside of both the humanitarian charity sector and the technical sector. They could be doing a technical job that is not in anyway related to humanitarian work. These are people that could support the technical people within humanitarian orgs to help the non-technical people contribute in ways in which they feel happy to. They may or may not have contributed to OS before.

**Persona 7 - For profit businesses - Fans.**
These are both the technical or non-technical people that sit in businesses and have some corporate responsibility. They could be allies and advocates and allow for the employees to ‘give back’ during charitable hours or facilitate and support events that engage with people in Charities/NGOs/Non-profit orgs.

**Comment by Erioldoesdesign** [comment]
## Visualise your support network

https://docs.google.com/presentation/d/18e5O3Yxz1lhqb5xnqve4ymmJhH5bl2J8vQx8bc_qqcw/edit?usp=sharing
