### ISSUE TITLE
AdaUnlocked!

### ISSUE THREAD

**Issue by alexhemming** [MozillaFestival/open-leaders-6#37]
Project Lead: @alexhemming

Mentor: @jaheppler

Welcome to OL6, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Sept 11): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 18): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol6-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 25): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 2): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by alexhemming** [comment]
AdaUnlocked! Vision Statement V1:
I’m working with young people and teachers in the UK to make digital puzzle games so that young people and teachers around the world can learn digital skills and create their own learning experiences.

**Comment by alexhemming** [comment]
AdaUnlocked! Open Canvas: 
http://bit.ly/adaunlocked-open-canvas

**Comment by alexhemming** [comment]
# Draft README:
## AdaUnlocked! 🔓

### 👋Hello world 🌍
**Welcome to the AdaUnlocked project!**
Hi, I'm Alex and I teach computer science to young people at Ada, the National College for Digital Skills in London, UK. I am passionate about creating learning expereinces, tools and workshops that will allow our young people to get actively involved in the digital sector and develop the skills they need to become digital pioneers.

The AdaUnlocked! project is part of this ongoing mission and it is awesome that you are taking the time to read about us. **We would love to have you join us as a contributor. 🤟** If the idea of joining us on our epic adventure has lit 

Say hello! Welcome people to the project. It’s great to introduce yourself here, so people know they’re dealing with a person or group of real people. Let potential contributors know you’re excited that they’re here to learn more
### Project description:
#### Vision:
Write a project description: what you’re doing, with who, for who, and why. Sound familiar? This is a version of your project vision. 
Expand your sentence as a full paragraph, adding any new details about aims and the problems you plan to solve that surfaced in the Open Canvas activity. Try to phrase this so it’s understandable and appealing to a wide variety of people, not just those in your field.
#### UVP:
Explain what makes your project special, useful, exciting! You can use the ideas you generated for “Unique Value Proposition” in your Open Canvas here.
## Get involved:
Show how to get started using or contributing to the project. If you’re just getting started, this could be as simple as asking people to attend a planning call or kick-off event, or sign up for an email newsletter about the project. If you’re not sure quite how to get users involved just yet, don’t worry! In the next module, you’ll devise some ways for newcomers to get involved, and create contributor guidelines. Once you’ve done the next module, and you can come back to this README and add a link to contributor guidelines to this section.
## Resources needed:
State what resources are most needed. If you have a need for a special kind of help, expertise, or a resource like event space, be sure to mention that here.

**Comment by alexhemming** [comment]
# DRAFT Roadmap
## Project mission & summary:
> We are working with educational communities to make puzzle games, so that young people can learn digital skills, engage in the world wide web safely and contribute to the development of a healthy internet.

Our goal is to create a locked box puzzle challenge, that can be played as a team, which has digitial puzzles that get the players thinking and learning about decentralisation, digital Inclusion, openness, privacy and security. The players will need to slove all of the digital puzzles, in order to generate the code to unlock their box and access the treasure within.

Example of an AdaUnlocked! game - https://adacollege.github.io/AdaUnlocked-Design-Jam/game/

## Milestones
### Milestone: Design
- [ ] Design a puzzle related to decentralisation.
- [ ] Design a puzzle related to digital Inclusion.
- [ ] Design a puzzle related to openness.
- [ ] Design a puzzle related to privacy and security.
- [ ] Design takeaway resource that allows players to create their own puzzles.

### Milestone: Develop
- [ ] Develop web app.
- [ ] Develop takeaway resource.
- [x] Build 10 boxes with hasps.
- [x] Source 10 combination locks.
- [x] Source 10 laptops.

### Milestone: [MozFest London, UK](https://mozillafestival.org/)
- [x] Organise volunteers.
- [x] Run sessions on Sunday 28th Oct 2018 12:45 to 13:45 level 2 room 205

### Milestone: Build Puzzle Collection
- [ ] Gallery of contributed puzzles.

**Comment by brendazam** [comment]
Hello Alex! First of all, I love your project, the things that I could tell you about your vision is that you could be more specific about the age of the games, using words like "young" brings abstract meanings, that could help you a little :) I hope this helped you and keep going, the project it's awesome! 

Btw, I love anime too 😄

Have an awesome day! Brenda

**Comment by alexhemming** [comment]
Thanks, @brendazam 😊 I'll have a think about the "young" / specific age abstract issue, I wanted to keep it open and not close off people who want to take part and I was worried if I went for playable by ages 10 to 16 it might cut off some people who'd like to take part.

Maybe I can work it by having an easy, medium and hard version which the players can then self-select and can change the wording of my vision to "people" instead of "young people".🤔

Thank you so much for your feedback, you've given me food for thought! And yes anime FTW 🙌

**Comment by estherhersh** [comment]
Hey Alex! Love your project and your open canvas is really clear. I would love to know more about the format of these puzzles and the contexts in which they would be solved (if they're online collaborative games, physical boxes etc.)

**Comment by alexhemming** [comment]
# DRAFT LICENCE

Non-software content in this project is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">AdaUnlocked!</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Alex Hemming</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. license.

**Comment by alexhemming** [comment]
> Hey Alex! Love your project and your open canvas is really clear. I would love to know more about the format of these puzzles and the contexts in which they would be solved (if they're online collaborative games, physical boxes etc.)

Hi @estherhersh thanks for reading my open canvas and the feedback! Here's a link to the first AdaUnlocked! puzzle set I created - https://adacollege.github.io/AdaUnlocked-Design-Jam/game/ - The team get given an acutall locked box with a combination padlock on it. They have to solve the digital puzzles in order to get the combination. 

However I am thinking about trying a more varied approach for the new puzzle set, perhaps bringing in other props and RL puzzles that need to be solved alongside the digital webpage puzzle.

**Comment by withshubh** [comment]
> # AdaUnlocked! Vision:
> **AdaUnlocked! Vision Statement V1:**
> 
> > _Working with young people and teachers in the UK to make digital puzzle games so that young people and teachers around the world can learn digital skills and create their own learning experiences._
> 
> **AdaUnlocked! Vision Statement V2:**
> 
> > _Working with educational communities to make puzzle games, so that young people can learn digital skills, engage in the world wide web safely and contribute to the development of a healthy internet._
> 
> **AdaUnlocked! Vision Statement V3:**
> 
> > _Working with educational communities to make puzzle games, so that players can learn digital skills, engage in the world wide web safely and contribute to the development of a healthy internet._
> 
> ## Notes:
> Might be too short? Too generic? Not enough detail?
> Should I explain in the statement that this is a "locked box" challenge as well, with users having to solve the puzzles to get the combo to open the lock and reach the prize?
> **Any feedback gratefully received, thanks!**

Hi,
Liked your draft, We are also working on a somewhat similar project to aware school and university students about Open Source & Mozilla and Our aim is also to promote women participate more in technical activities in Guna region.

**Comment by withshubh** [comment]
> # AdaUnlocked! Open Canvas:
> http://bit.ly/adaunlocked-open-canvas

Hey,
Liked you Open Canvas. Fits perfectly with your vision statement! 👍
