### ISSUE TITLE
U.S. Forms System

### ISSUE THREAD

**Issue by annekainicUSDS** [MozillaFestival/open-leaders-6#71]
Project Lead: @annekainicUSDS

Mentor: @ecleipteon

Welcome to OL6, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Sept 12): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 19): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol6-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 26): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 3): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by annekainicUSDS** [comment]
Draft vision statement:

We are working to improve the most common interaction between the government and the public, completing forms, so that people can better access the services and benefits they need. We are working open because we believe that open-sourcing software in the government, where possible, builds trust, promotes transparency, and ensures the best ideas are shaping our government.

**Comment by annekainicUSDS** [comment]
1. Open Canvas: https://docs.google.com/presentation/d/1vNe3QY8NPFSht6BTgLfyS1pUJLlt0AWKwUY3zEV1sM4/edit?usp=sharing
2. Roadmap:

**Comment by annekainicUSDS** [comment]
### Roadmap

#### Milestone: Completely extract references to original source code
We want our library to be completely separate from the original source code in which it was created. While most of this work was already completed, there are a few remaining items to clean up, captured in the following ticket.
[#211: Eliminate Vets.gov-isms](https://github.com/usds/us-forms-system/issues/211)

#### Milestone: Reimagine design and architecture of the library
Now that the library is a stand-alone product, what new direction might we want to take it in? How can we rethink some of the original design decisions to make them better and more scalable?
[#257: Investigate pulling out routing](https://github.com/usds/us-forms-system/issues/257)
[#205: Swappable architecture](https://github.com/usds/us-forms-system/issues/205)
[#203: User research](https://github.com/usds/us-forms-system/issues/203)
[#201: Non-linear navigation](https://github.com/usds/us-forms-system/issues/201)
[#283: Form builder](https://github.com/usds/us-forms-system/issues/283)
[#226: Explore generating pdfs of form output](https://github.com/usds/us-forms-system/issues/226)
[#170: Internationalization](https://github.com/usds/us-forms-system/issues/170)
[#141: Relationship with react-jsonschema-form library](https://github.com/usds/us-forms-system/issues/141)

#### Milestone: Stabilize the code and the process around it
We're still working through issues of publishing, documenting, and relationship with the open community. There are some concrete actions we can take here around this to make our project more stable.
[#270: New release process](https://github.com/usds/us-forms-system/issues/270)
[#218: Do not commit build artifacts](https://github.com/usds/us-forms-system/issues/218)
[#210: Versioning data and schema](https://github.com/usds/us-forms-system/issues/210)
[#104: What the library is and isn't](https://github.com/usds/us-forms-system/issues/104)
[#200: Reference documentation site](https://github.com/usds/us-forms-system/issues/200)
[#193: Design audit](https://github.com/usds/us-forms-system/issues/193)

**Comment by fraguada** [comment]
Important work you are doing! The vision statement is clear and concise. I've been following the Barcelona government open participation platform ['decidim'](https://github.com/AjuntamentdeBarcelona/decidim-barcelona) develop over the years. While the objective is different than the U.S. Forms System (has more to do with citizen participation in government), I think it is interesting to see governments open sourcing projects.

**Comment by owenjoseph** [comment]
Hey @fraguada, I came here to browse our cohort's vision statements, and now I'm diving into 'decidim,' which sounds like it has some mission-overlap w/ our project. Thanks for sharing!

@annekainicUSDS Great vision statement - articulates the practicality as well as the immense importance of the project. Awesome!

**Comment by annekainicUSDS** [comment]
### License
License: ISC
Link: https://github.com/usds/us-forms-system/blob/master/package.json#L25

### README
Link: https://github.com/usds/us-forms-system/blob/master/README.md
