### ISSUE TITLE
Beware of your Privacy!

### ISSUE THREAD

**Issue by diwanshi** [MozillaFestival/open-leaders-6#72]
Project Lead: @diwanshi

Mentor: @wathagindungu

Welcome to OL6, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Sept 11): Your first mentorship call
- [ ] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [ ] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Sept 18): First Cohort Call (Open by Design)
- [ ] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [ ] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [ ] Check the [Syllabus](https://mzl.la/ol6-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Sept 25): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Oct 2): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

This issue is here to help you keep track of work during the first month of the program. Please refer to the [OL6 Syllabus](https://mzl.la/ol6-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by diwanshi** [comment]
Draft 1: 
Our online lives have become our real life to a larger extent and no matter how much we want, we can’t escape it leaving our personal data vulnerable to people who can use it for their benefit or even against us.
Every other day we hear about major privacy breaches or related scam but not much we do about it. It's not that people aren’t concerned about their privacy but either unaware of the risks or multiple options they can use to minimize the vulnerability and grow with the current technologies at the same time.
For a long time now, we have been discussing, teaching, advocating, creating resources, writing articles about privacy for people. The major problem is that this valuable information is scattered all over the web and not every person wouldn’t prefer to invest their time in researching all these resources.

I am working with the Mozilla community to build a tool which has all the privacy-related resources so that anybody can easily browse through based on their scenarios, get the relevant information from multiple sources in a single place.

Draft 2: I am working with Mozilla Community to build a privacy-related tool so that anybody can access privacy-related resources in a single place instead of browsing through multiple platforms to understand how important Privacy is for each individual.

**Comment by diwanshi** [comment]
I know Draft 1st is a bit long but I wanted to communicate my "Why" through it.
Any feedback is appreciated

**Comment by amchagas** [comment]
Hi @diwanshi,

Cool project! I like the idea of having a long and short versions :+1: 
also, you probably already know this, but there are some [Mozilla Fellows](https://blog.mozilla.org/blog/2018/08/21/mozilla-announces-25-new-fellows-in-openness-science-and-tech-policy/) working on issues that are related to your project, maybe it is a good idea to reach out to them and start a conversation?

**Comment by alexhemming** [comment]
Your project sounds amazing! I'm a computer science teacher and a large chunk of our course is focused on data privacy and safety online. I'm constantly getting lost in the reams of content available on the web about this. It would be an incredible resource if the most valuable, active and useful resources and info were collated and organised. Teachers & parents everywhere will be thank you!
Like your distilled vision statement draft2, it is easy to understand and clearly states your aim.
If you need any help on your project from an education/computer science teacher pov please let me know :)

**Comment by diwanshi** [comment]
@alexhemming ,

Yes, that's exactly the pain area I am trying to hit and solve. Once I start the development, I'd like to have your feedback as a Teacher, as well as It, 'd be great If I can get some feedback from student's perspective (maybe you can help there if possible).

Thanks for your feedback on Vision statement. I'll try to polish it more.

**Comment by npatil99** [comment]
This is pretty fresh idea Diwanshi. We all care for privacy but unfortunately very few of us are serious about being cautious about it. 

Looking from an end user perspective who has limited or no technology background. You may need to define a privacy-related resources a bit more..

**Comment by rajasekharponakala** [comment]
Your idea is nice. I've seen your Draft1,2, looks nice. It is glad that you want to help the community to know and more reach of privacy!, as this is a right need of the hour.  Looking forward to help!.

**Comment by tejasri19** [comment]
Your idea is great. Do you have a vision statement to learn more?

**Comment by diwanshi** [comment]
[Open Canvas ](https://docs.google.com/presentation/d/1rFTN8F5e_EJnizBUoukupLZTEtPZyVN9AfCIWxM7zHM/edit?usp=sharing)

**Comment by diwanshi** [comment]
### Draft README
------------------------------
### Beware of your privacy!!!

Our online lives have become our real life to a larger extent and no matter how much we want, we can’t escape it leaving our personal data vulnerable to people who can use it for their benefit or even against us.
Every other day we hear about major privacy breaches or related scam but not much we do about it. It's not that people aren’t concerned about their privacy but either unaware about the risks or multiple options they can use to minimise the vulnerability and grow with the current technologies at the same time.

Since a long time now, we have been discussing, teaching, advocating, creating resources, writing articles about privacy for people. The major problem is that this valuable information is scattered all over the web and not every person wouldn’t prefer to invest their time in researching all these resources.

What if we provide them with a tool which has all the privacy related resources which user can easily browse through and get the relevant information from multiple sources in a single place.

### The Idea:
Is to develop a tool with an user friendly interface that has privacy scenarios that can be selected by the user and gets them the risks and open source tools/extensions they can use in that scenario. These scenarios and associated risks and solutions can be submitted by anyone on github as issues/PRs and reviewed by the privacy enthusiasts and experts in the community.

This tool can be used as a resource pool for Privacy Month as well. I have myself contributed to Privacy months before and the pain points I have faced and observed while organizing it were:

- Getting all the resources in a single place
   - Reviewing them for the content
   - Who will review?
   - Accuracy of the content
   - Research about the options mentioned as a solution for ex: People suggest various ad blocker tools but in the backend they share the information without showing you any advertisements.
- Graphic designs
   - Who will create graphics for each scenario or a privacy tip?
   - Getting them ready on time.
- Transparency and Contributions from the global community
   - Who are the reviewers?
   - How others can contribute to privacy month?
   - How global communities can adopt the format?

I think that this tool can help address the above points by giving people a transparent platform where people from any open source community can contribute to it in many ways like designing graphics, providing scenarios and tips, review and make use of it efficiently.

Below are the few examples:
**Scenario 1 : Email Communication**

**Risks**: 
- **Virus Attacks** while opening emails and email attachments or visiting unfriendly links in emails on computers
- **Trojans** in Your Midst these attacks are quick, unexpected, and brutal. Trojans are executable files that cause devastation in their wake and all it takes is for you to click on the wrong email link.
- **Unencrypted Emails** can be read by any bad actors or governments with access to the networks they travel through.
Many more….

**Solutions (Wanna do something about it?):**
- Do not open any link in emails which has come through a unfriendly email ids asking about financial or personal information or claiming you have won something.
- Use Encryption. <How to(s)>
- Open Source Tools: 
   - ProtonMail
   - MailPile

**Scenario 2: Search Engines**

**Risks:**
- Data Leaks
- Cookies
- Tracking
- CIA & NSA Ties

**Solutions:**
- Private Browsing
- Use Search engine that doesn’t track you
   - [Duck Duck Go](https://duckduckgo.com/)
   - [searX](https://searx.me/)
   - [StartPage](https://www.startpage.com/)
   - [Privatelee](https://privatelee.com/)

There are so many more scenarios. The idea is to present this information in an interactive and user friendly way.

**Comment by diwanshi** [comment]
Link to [Draft ReadMe](https://docs.google.com/document/d/1eL27U3gch2U29e11o75MsBbFhw4zgRTN8Ybvj6gv2k8/edit?usp=sharing).

Any Suggestions and Feedback is appreciated.
Thanks

**Comment by diwanshi** [comment]
# **Draft Roadmap**

## Project Mission and Summary

> I am working with Mozilla Community to build an application to provide netizens with consolidated, scenario based privacy related resources with risks and the probable solutions that they can opt for,  at a single place.

Our online lives have become our real life to a larger extent and no matter how much we want, we can’t escape it leaving our personal data vulnerable to people who can use it for their benefit or even against us.
Every other day we hear about major privacy breaches or related scam but not much we do about it. It's not that people aren’t concerned about their privacy but either unaware about the risks or multiple options they can use to minimise the vulnerability and grow with the current technologies at the same time.

Since a long time now, we have been discussing, teaching, advocating, creating resources, writing articles about privacy for people. The major problem is that this valuable information is scattered all over the web and not every person wouldn’t prefer to invest their time in researching all these resources.

What if we provide them with a tool which has all the privacy related resources which user can easily browse through and get the relevant information from multiple sources in a single place.

## Milestones

### Planning

- [ ] Plan the architecture of the application.
- [ ] Have a call with technical experts to have suggestions on the architecture of the app.
- [ ] Decide, how the app will handle the data. Can the data be mined or needs to be enetered by maintainers and reviewers of the application from the community.
- [ ] Decide on the technologies to be used on front-end and the backend

### Design
- [ ] Create wireframes / mockups of how the app will look.
- [ ] Take initial feedback on the wireframes from fellow open leaders, mentors, experts.
- [ ] Create a workflow diagram/document for the review process.

### Develop
- [ ] Develop the backend
- [ ] Develop the frontend UI.
- [ ] Research the privacy resources.
- [ ] Host the app (initially on heroku)
- [ ] Start adding data to the application.

**Comment by chadsansing** [comment]
Here is an educator-facing [privacy & security toolkit](https://mozilla.github.io/curriculum-final/privacy-toolkit-v10.pdf) we assembled last year; the second page, in particular, has resources that might be useful to include in your project.

**Comment by chadsansing** [comment]
Re: language, I would focus on a very specific module, like, "Why should you care about privacy/2fa on mobile apps?", then collect stories and examples to illustrate problems, then suggest 1 resource per problem as a solution, then provide some further reading. Keep things very direct, clear, and connected.

Test out 2 or 3 versions of the same content with different copy/language, and then revise to use the language that works best for the audience you want to reach.

Work on developing that process for 1 module and then apply that same process to the development of later modules if you are the only one doing the work right now.

**Comment by chadsansing** [comment]
This also reminds me of an activity you could remix from Thimble/our curriculum, called Hacker Cards.

- [Thimble](https://thimbleprojects.org/mozillalearning/308795/)
- [GitHub](https://github.com/mozilla/curriculum-final/tree/gh-pages/privacy-rock-paper-scissors)

**Comment by chadsansing** [comment]
See also: https://foundation.mozilla.org/en/privacynotincluded/ and https://www.mozillapulse.org/featured.

**Comment by diwanshi** [comment]
@chadsansing Thanks a lot for these resources. They are great and surely help me a ton.
